#pragma once

#include "Core/Figures/Angular.hpp"
#include "Core/Figures/Sprite.hpp"
#include "Core/Figures/Primitives/Triangle.hpp"
#include "Core/Figures/Primitives/Tetragon.hpp"
#include "Core/Figures/Primitives/Polygon.hpp"
#include "Core/Figures/Primitives/Line.hpp"
#include "Core/Figures/Primitives/Ellipse.hpp"
#include "Core/Figures/Primitives/LineStrip.hpp"
#include "Core/Figures/Primitives/Points.hpp"
#include "Core/Windows/Window.hpp"
#include "Core/Windows/RenderingAdapter.hpp"
#include "Core/DrawableCollection.hpp"
#include "Core/Figures/Views.hpp"
#include "Core/Textures/TextureLoader.hpp"
#include "Core/Text/UTF-8.hpp"
#include "Core/Text/Text.hpp"
