#pragma once

#include "Core/Window.hpp"
#include "Core/Shapes/Angular.hpp"
#include "Core/Shapes/Sprite.hpp"
#include "Core/Shapes/Primitives/Triangle.hpp"
#include "Core/Shapes/Primitives/Tetragon.hpp"
#include "Core/Shapes/Primitives/Polygon.hpp"
#include "Core/Shapes/Primitives/Line.hpp"
#include "Core/Shapes/Primitives/Ellipse.hpp"
#include "Core/Shapes/Primitives/LineStrip.hpp"
#include "Core/Shapes/Primitives/Points.hpp"
#include "Core/DrawableCollection.hpp"
#include "Core/Shapes/Views.hpp"
#include "Core/TextureLoader.hpp"
#include "Core/Text/UTF-8.hpp"
#include "Core/Text/Text.hpp"
